### ISSUE TITLE
Allow `latest` as option

### ISSUE THREAD

**Issue by carlopi** [PMassicotte/duckfetch#5]
Idea would be to fetch binaries available from: https://duckdb.org/docs/installation/?version=main&environment=cli&platform=linux&download_method=direct&architecture=x86_64 (for example).

Here problem would be if reinstalling actually means fetching /checking a new one, it does add some logic, but I guess it can be handy.

**Comment by PMassicotte** [comment]
Initial working implementation

https://github.com/PMassicotte/duckfetch/tree/latest-nightly

**Comment by PMassicotte** [comment]
Implemented in a12581dd0d38a54598fa21f931c380d674daa13e
